import Foundation
import SwiftUI

public enum AppLanguage: String, CaseIterable, Identifiable, Codable {
    case vietnamese = "vi"
    case english = "en"
    
    public var id: String { rawValue }
    
    public var displayName: String {
        switch self {
        case .vietnamese: return "Tiếng Việt"
        case .english: return "English"
        }
    }
}

public class LocalizationManager: ObservableObject {
    @Published public var currentLanguage: AppLanguage = .vietnamese
    
    private let viDictionary: [String: String] = [
        "appName": "QuizMaster",
        "appTagline": "Ứng dụng Ôn tập & Tạo Đề thi Trắc nghiệm",
        "projects": "Danh sách Dự án",
        "noProjects": "Chưa có dự án nào",
        "addProject": "Thêm Dự án mới",
        "newProject": "Thêm Dự án mới",
        "toggleShuffle": "🔀 Xáo trộn câu hỏi & đáp án",
        "projectName": "Tên dự án",
        "newProjectTitle": "Tạo Dự án Mới",
        "projectNamePlaceholder": "Tên dự án mới...",
        "create": "Tạo",
        "createProject": "Tạo Dự án",
        "deleteProject": "Xóa Dự án",
        "deleteQuiz": "Xóa Bộ đề",
        "renameQuiz": "Đổi tên Bộ đề",
        "resetProgress": "Đặt lại Tiến độ học",
        "noProjectsYet": "Chưa có dự án nào",
        "createFirstProjectPrompt": "Hãy bấm nút '+' để tạo dự án học tập đầu tiên.",
        "projectQuizzesHeader": "Các Bộ đề thi trong Dự án",
        "noQuizzesInProject": "Dự án này chưa có bộ đề thi nào.",
        "importDoc": "Nhập Tài liệu / Bộ đề",
        "exportZip": "Xuất gói Zip Bundle (Mặc định - Hỗ trợ nhập lại)",
        "exportWordDocx": "Xuất tệp Word (.docx)",
        "orImportPremade": "Hoặc Nhập bộ đề thi có sẵn (Zip Bundle / JSON)",
        "practiceMode": "Luyện tập",
        "examMode": "Thi thử",
        "flashcardMode": "Thẻ ghi nhớ",
        "settings": "Cài đặt",
        "settingsTitle": "Cài đặt Ứng dụng",
        "apiKeyLabel": "Google AI Studio API Key",
        "apiKeyHint": "Dán API Key từ Google AI Studio...",
        "testApiKey": "Kiểm tra API Key",
        "apiKeyValid": "✓ API Key hợp lệ và hoạt động bình thường!",
        "apiKeyInvalid": "✕ API Key không hợp lệ hoặc hết hạn ngạch.",
        "modelLabel": "Mô hình AI",
        "modelFixedNote": "Cố định Gemini 3.5 Flash Lite cho độ chính xác cao.",
        "directoriesHeader": "Thư mục Mặc định",
        "inputDirLabel": "Thư mục Nhập tài liệu mặc định:",
        "outputDirLabel": "Thư mục Xuất kết quả mặc định:",
        "selectFolder": "Chọn thư mục",
        "languageLabel": "Ngôn ngữ ứng dụng:",
        "themeLabel": "Chủ đề giao diện:",
        "themeSystem": "Tự động",
        "themeLight": "Sáng",
        "themeDark": "Tối",

        "saveSettings": "Lưu Cài đặt",
        "questionsCount": "câu hỏi",
        "quizzesCount": "bộ đề thi",
        "masteryLevel": "Mức độ thuộc bài",
        "quitQuiz": "Thoát bài thi",
        "progressFormat": "Câu %@ / %@",
        "scoreHiddenNote": "Đáp án hiển thị ngay sau khi chọn",
        "questionHeader": "Câu hỏi",
        "correctAnswer": "ĐÚNG RỒI!",
        "wrongAnswer": "CHƯA CHÍNH XÁC",
        "nextQuestion": "Câu tiếp theo",
        "prevCard": "Thẻ trước",
        "questionNavPane": "Danh sách câu hỏi",
        "finishPractice": "Hoàn thành bài luyện tập",
        "quizFinishedTitle": "Hoàn thành bài Luyện tập!",
        "quizFinishedSubtitle": "Bạn đã duyệt qua toàn bộ câu hỏi trong bộ đề.",
        "btnRedoWrongOnly": "Làm lại các câu làm SAI",
        "btnReviewWithAnswers": "Xem lại toàn bộ đáp án & giải thích",
        "backToDashboard": "Về màn hình chính",
        "backToProjects": "Về danh sách Dự án",
        "questionSide": "MẶT CÂU HỎI",
        "answerSide": "MẶT ĐÁP ÁN ĐÚNG",
        "yourChoice": "Đáp án bạn chọn:",
        "correctChoice": "Đáp án đúng:",
        "filterAll": "Tất cả câu hỏi",
        "filterWrong": "Chỉ câu làm sai",
        "reviewTitle": "Xem lại Đáp án & Giải thích Chi tiết",
        "confirmScanTitle": "Xác nhận Chế độ Quét Tài liệu",
        "confirmScanMsgToggleOn": "⚠️ Bạn đang BẬT 'Tạo câu hỏi trắc nghiệm tự động'. Hãy chắc chắn đây là TÀI LIỆU BÀI GIẢNG / VĂN BẢN THƯỜNG (không phải đề thi có sẵn). AI sẽ tự động phân tích và tạo câu hỏi.",
        "confirmScanMsgToggleOff": "⚠️ Bạn đang TẮT 'Tạo câu hỏi trắc nghiệm tự động'. Ứng dụng sẽ trích xuất ĐỀ THI CÓ SẴN từ file. Hãy chắc chắn tài liệu đã có sẵn các câu hỏi và đáp án.",
        "geminiLangNote": "💡 Lưu ý: Khi chuyển ngôn ngữ ứng dụng sang Tiếng Anh, Gemini AI cũng sẽ tự động tạo toàn bộ câu hỏi trắc nghiệm, các phương án và giải thích bằng TIẾNG ANH (và ngược lại).",
        "checkUpdates": "Kiểm tra Cập nhật",
        "updateAvailableTitle": "Bản cập nhật Mới đã sẵn sàng!",
        "youAreUpToDate": "Bạn đang sử dụng phiên bản mới nhất!",
        "downloadUpdate": "Tải về Bản cập nhật Mới ↗",
        "currentVersionLabel": "Phiên bản hiện tại:",
        "latestVersionLabel": "Phiên bản mới nhất trên GitHub:",
        "releaseNotesLabel": "Thông tin Bản cập nhật Mới:",
        "scanningGemini": "Gemini 3.5 Flash Lite đang phân tích và quét tài liệu...",
        "geminiScannerHeader": "Quét & Nhận diện Tài liệu với Gemini 3.5 Flash Lite",
        "selectDocFilePrompt": "Chọn tệp tài liệu (Word .docx / PDF / TXT):",
        "noFileSelected": "Chưa chọn tệp...",
        "selectFileBtn": "Chọn tệp...",
        "quizTitlePlaceholder": "Tên bộ đề mới (Tùy chọn)...",
        "enableAutoGenerate": "Bật \"Tạo câu hỏi trắc nghiệm tự động\" từ tài liệu văn bản thường",
        "depthModeHeader": "Độ phủ & Mức độ chi tiết của câu hỏi (Depth Mode):",
        "startGeminiScanBtn": "Bắt đầu Quét với Gemini AI",
        "exportZipImmediate": "Xuất ngay file Zip (RTF Bundle)",
        "exportWordImmediate": "Xuất ngay file Word (.docx)",
        "selectQuizFilePrompt": "Chọn tệp bộ đề (.zip hoặc .json):",
        "selectQuizBtn": "Chọn tệp đề...",
        "importPremadeBtn": "Nhập Bộ Đề Có Sẵn vào Dự án",
        "close": "Đóng",
        "cancel": "Hủy",
        "confirm": "Xác nhận",
        "multiSelectMode": "Chọn nhiều bộ đề",
        "exitMultiSelect": "Thoát Chọn nhiều",
        "moveToOtherProject": "Chuyển sang Dự án khác...",
        "moveQuizTitle": "Chuyển Bộ đề thi",
        "selectTargetProject": "Chọn Dự án đích muốn chuyển bộ đề tới:",
        "confirmMove": "Xác nhận Chuyển",
        "noOtherProjectsMsg": "Chưa có dự án nào khác. Hãy tạo một dự án mới ở Sidebar trước khi chuyển."
    ]
    
    private let enDictionary: [String: String] = [
        "appName": "QuizMaster",
        "appTagline": "Study & Multiple-Choice Test Generator",
        "projects": "Projects List",
        "noProjects": "No projects yet",
        "addProject": "New Project",
        "newProject": "New Project",
        "toggleShuffle": "🔀 Shuffle Questions & Options",
        "projectName": "Project Name",
        "newProjectTitle": "Create New Project",
        "projectNamePlaceholder": "New project name...",
        "create": "Create",
        "createProject": "Create Project",
        "deleteProject": "Delete Project",
        "deleteQuiz": "Delete Quiz",
        "renameQuiz": "Rename Quiz",
        "resetProgress": "Reset Progress",
        "noProjectsYet": "No projects yet",
        "createFirstProjectPrompt": "Click '+' to create your first study project.",
        "projectQuizzesHeader": "Project Quiz Sets",
        "noQuizzesInProject": "This project has no quiz sets yet.",
        "importDoc": "Import Document / Quiz",
        "exportZip": "Export Zip Bundle (Default - Importable)",
        "exportWordDocx": "Export Word (.docx)",
        "orImportPremade": "Or Import Pre-made Quiz Set (Zip / JSON)",
        "practiceMode": "Practice (Multiple-Choice)",
        "examMode": "Exam Mode",
        "flashcardMode": "Flashcard Mode",
        "settings": "Settings",
        "settingsTitle": "App Settings",
        "apiKeyLabel": "Google AI Studio Key (Gemini API)",
        "apiKeyHint": "Paste your Google AI Studio API Key here...",
        "testApiKey": "Test API Key",
        "apiKeyValid": "✓ API Key is valid and active!",
        "apiKeyInvalid": "✕ Invalid API Key or rate limit exceeded.",
        "modelLabel": "AI Model",
        "modelFixedNote": "Model locked to Gemini 3.5 Flash Lite for high accuracy.",
        "directoriesHeader": "Default Directories",
        "inputDirLabel": "Default Document Input Folder:",
        "outputDirLabel": "Default Result Output Folder:",
        "selectFolder": "Browse...",
        "languageLabel": "App Language:",
        "themeLabel": "App Theme:",
        "themeSystem": "System Default",
        "themeLight": "Light Mode",
        "themeDark": "Dark Mode",
        "saveSettings": "Save Settings",
        "questionsCount": "questions",
        "quizzesCount": "quiz sets",
        "masteryLevel": "Mastery Level",
        "quitQuiz": "Quit Quiz",
        "progressFormat": "Question %@ of %@",
        "scoreHiddenNote": "Feedback shown immediately after selection",
        "questionHeader": "Question",
        "correctAnswer": "CORRECT!",
        "wrongAnswer": "INCORRECT",
        "nextQuestion": "Next Question",
        "prevCard": "Previous Card",
        "questionNavPane": "Question Navigator",
        "finishPractice": "Finish Practice",
        "quizFinishedTitle": "Practice Completed!",
        "quizFinishedSubtitle": "You have reviewed all questions in this set.",
        "btnRedoWrongOnly": "Redo Wrong Questions Only",
        "btnReviewWithAnswers": "Review All Answers & Explanations",
        "backToDashboard": "Back to Main Dashboard",
        "backToProjects": "Back to Projects List",
        "questionSide": "QUESTION SIDE",
        "answerSide": "CORRECT ANSWER SIDE",
        "yourChoice": "Your choice:",
        "correctChoice": "Correct answer:",
        "filterAll": "All Questions",
        "filterWrong": "Wrong Questions Only",
        "reviewTitle": "Detailed Answer Review & Explanations",
        "confirmScanTitle": "Confirm Document Scanning Mode",
        "confirmScanMsgToggleOn": "⚠️ You ENABLED 'Create Multiple-Choice'. Please confirm your file is a REGULAR LECTURE / TEXT DOCUMENT (not a pre-made quiz). Gemini will generate test questions automatically.",
        "confirmScanMsgToggleOff": "⚠️ You DISABLED 'Create Multiple-Choice'. The app will extract PRE-EXISTING QUIZ QUESTIONS from the file. Please confirm the file already contains quiz questions and answers.",
        "geminiLangNote": "💡 Note: Changing the app language to English will instruct Gemini AI to generate all future quiz questions, options, and explanations in English (and vice versa).",
        "checkUpdates": "Check for Updates",
        "updateAvailableTitle": "New Update Available!",
        "youAreUpToDate": "You are using the latest version!",
        "downloadUpdate": "Download New Release ↗",
        "currentVersionLabel": "Current Version:",
        "latestVersionLabel": "Latest Version on GitHub:",
        "releaseNotesLabel": "What's New in This Build:",
        "scanningGemini": "Gemini 3.5 Flash Lite is scanning and analyzing the document...",
        "geminiScannerHeader": "Scan & Process Document with Gemini 3.5 Flash Lite",
        "selectDocFilePrompt": "Select document file (Word .docx / PDF / TXT):",
        "noFileSelected": "No file selected...",
        "selectFileBtn": "Browse...",
        "quizTitlePlaceholder": "New Quiz Title (Optional)...",
        "enableAutoGenerate": "Enable \"Auto-generate Multiple-Choice Quizzes\" from text documents",
        "depthModeHeader": "Question Coverage & Detail Level (Depth Mode):",
        "startGeminiScanBtn": "Start Scanning with Gemini AI",
        "exportZipImmediate": "Export Zip (RTF Bundle)",
        "exportWordImmediate": "Export Word (.docx)",
        "selectQuizFilePrompt": "Select quiz file (.zip or .json):",
        "selectQuizBtn": "Browse...",
        "importPremadeBtn": "Import Pre-made Quiz into Project",
        "close": "Close",
        "cancel": "Cancel",
        "confirm": "Confirm",
        "multiSelectMode": "Select Multiple Quizzes",
        "exitMultiSelect": "Exit Multi-Select",
        "moveToOtherProject": "Move to Another Project...",
        "moveQuizTitle": "Move Quiz Set",
        "selectTargetProject": "Select target project to move quiz to:",
        "confirmMove": "Confirm Move",
        "noOtherProjectsMsg": "No other projects available. Create a new project in the sidebar first."
    ]
    
    public init() {}
    
    public func text(_ key: String) -> String {
        let dict = currentLanguage == .vietnamese ? viDictionary : enDictionary
        return dict[key] ?? key
    }
}
